FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app

ENV ASPNETCORE_HTTP_PORTS=8080
EXPOSE 8080

COPY artifacts/publish/ .

USER $APP_UID
ENTRYPOINT ["dotnet", "RusAuth.Authorization.Example.dll"]
