apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rusauth-authorization-example.fullname" . }}-config
  labels:
    {{- include "rusauth-authorization-example.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.appConfig.aspnetcoreEnvironment | quote }}
  ASPNETCORE_HTTP_PORTS: {{ .Values.appConfig.aspnetcoreHttpPorts | quote }}
  AllowedHosts: {{ .Values.appConfig.allowedHosts | quote }}
  RusAuth__BaseUrl: {{ .Values.appConfig.rusAuthBaseUrl | quote }}
  RusAuth__TimeOut: {{ .Values.appConfig.rusAuthTimeout | quote }}
  DataProtection__KeyRingPath: {{ .Values.appConfig.dataProtectionKeyRingPath | quote }}
  Logging__LogLevel__Default: {{ .Values.appConfig.logging.default | quote }}
  Logging__LogLevel__Microsoft__AspNetCore: {{ .Values.appConfig.logging.microsoftAspNetCore | quote }}
