nameOverride: ""
fullnameOverride: ""

replicaCount: 1

deployment:
  stamp: ""

image:
  repository: ghcr.io/rusauth/rusauth-authorization-example
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  port: 8080

appConfig:
  aspnetcoreEnvironment: Production
  aspnetcoreUrls: http://+:8080
  allowedHosts: "*"
  rusAuthBaseUrl: https://rusauth.ru/auth-client-api/
  rusAuthTimeout: 15
  dataProtectionKeyRingPath: /var/lib/rusauth-authorization-example/data-protection
  logging:
    default: Information
    microsoftAspNetCore: Warning

podSecurityContext:
  fsGroup: 1654

persistence:
  enabled: true
  existingClaim: ""
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  mountPath: /var/lib/rusauth-authorization-example/data-protection

existingSecretName: rusauth-authorization-example-secrets

gateway:
  name: edge
  namespace: gateway-system
  sectionNames:
    - http
    - https
  hostnames:
    - example-demo.rusauth.ru
  pathPrefix: /

callbackProtection:
  enabled: true
  path: /api/rusauth/callback/confirmation
  rateLimit:
    average: 2
    period: 1m
    burst: 2
  inFlightReq:
    amount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
