nameOverride: ""
fullnameOverride: ""

replicaCount: 1

deployment:
  stamp: ""

image:
  repository: ghcr.io/rusauth/rusauth-authorization-example
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  port: 8080

appConfig:
  aspnetcoreEnvironment: Production
  aspnetcoreUrls: http://+:8080
  allowedHosts: "*"
  rusAuthBaseUrl: https://rusauth.ru/auth-client-api/
  rusAuthTimeout: 15
  logging:
    default: Information
    microsoftAspNetCore: Warning

existingSecretName: rusauth-authorization-example-secrets

gateway:
  name: edge
  namespace: gateway-system
  sectionNames:
    - http
    - https
  hostnames:
    - example-demo.rusauth.ru
  pathPrefix: /

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

